-- NO se puede revertir.
--
-- La fusión borra el producto origen y suma el stock de una variante en la que
-- quedó: separar "3 unidades" de vuelta en "1 + 2" es una suposición, no un
-- dato — nada dice cuál de las dos filas trajo cuál unidad.
--
-- Lo que SÍ queda para reconstruirla a mano si hiciera falta: las dos mitades
-- del movimiento en `movimientos_stock` (el +2 y el -2 con origen
-- EDICION_VARIANTES) y las líneas del remito, que conservan `raw_nombre` y
-- `variante_match`.
--
-- Por eso la feature de fusionar tiene que mostrar una preview exacta ANTES de
-- ejecutar: es la única oportunidad de arrepentirse.
select 'Sin rollback: la fusion de productos es irreversible por diseno' as nota;
